version: '3.9'

services:
  mtg-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtg-node
    ports:
      - "8080:8080" # Internal Node.js app port
    env_file:
      - database.env
    volumes:
      - ./app:/app
      - ./ca-certificate.crt:/app/ca-certificate.crt

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - mtg-node